import Head from "next/head";
import Dashboard from "@/Layouts/Dashboard";
import { Session } from "@supabase/supabase-js";
import { GetServerSideProps } from "next";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import supabase from "@/utils/supabaseClient";

export default function DashboardPage() {
  const router = useRouter();
  const [sessionToken, setSessionToken] = useState<Session | null>();

  useEffect(() => {
    async function loginCheck() {
      const { data } = await supabase.auth.getSession();

      if (!data?.session?.user) {
        router.replace("/");
      } else {
        setSessionToken(data?.session);
      }
    }
    loginCheck();
  }, [router]);

  return (
    <>
      <Head>
        <title>Neuratwin </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Dashboard sessionToken={sessionToken!} />
      </main>
    </>
  );
}
